services:
  postgres:
    image: postgres:16
    container_name: dbeng-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: dbeng_lab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "log_min_duration_statement=0"

  adminer:
    image: adminer
    container_name: dbeng-lab-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
